[package]
name = "rnamed"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.1"
rayon = "1.8.0"
sha2 = "0.10.8"
