[package]
name = "rnamed"
version = "1.0.1"
edition = "2021"
authors = ["Kosette"]
description = "A simple tool to rename files to their blake3 checksum"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.5"
clap = { version = "4.5", features = ["derive"] }
glob = "0.3"
rayon = "1.10"
